# Numpy

Numpy:- Numpy stands for numerical python and is the core library for numeric and scientific computing, 
    It consists of multi_dimentional array objects 


- Its an homogeneous in nature the numpy list contains single datatype
- The array which we are using will doesnot supports multi dimentional, It only allows 1(single dimention).
- So to work on multidimention array we use 3rd party package called Numpy

### Load in NumPy (remember to pip install numpy first)

In [1]:
# !pip install numpy

In [2]:
import numpy as np

### The Basics

In [3]:
num = np.array([1, 2, 3])
num

array([1, 2, 3])

In [4]:
a = np.array([1,2,3], dtype='int32')      # it is not mandate to mention the datatype
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print("it's an float value=\n",b, "\n",b.dtype)  


b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.9]],dtype="int64")          #if you give int here it will convert in to int and gives you the flore value
print("\nit's an int value =\n",b,"\n",b.dtype)

it's an float value=
 [[9. 8. 7.]
 [6. 5. 4.]] 
 float64

it's an int value =
 [[9 8 7]
 [6 5 4]] 
 int64


In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get Dimension
b.ndim

2

In [8]:
b

array([[9, 8, 7],
       [6, 5, 4]], dtype=int64)

In [9]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
b.dtype

dtype('int64')

In [11]:
# Data Type
type(b)

numpy.ndarray

In [12]:
# Get Size
b.itemsize             # because its an integer (int8=itemsize=1,int16=2,int32=4,int64=8)    it gives only for 1 item

8

In [13]:
# Get number of elements
b.size

6

In [14]:
# Get total size, where total size(nbytes) = a.size*a.itemsize
b.nbytes     #(itemsize*size)

48

In [15]:
b.itemsize * b.size

48

### Accessing/Changing specific elements, rows, columns, etc

In [16]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [r, c]
a[0, -1]

7

In [18]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [20]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
# Getting a little more fancy [startindex:stopindex:stepsize]
a[0, ::2]

array([1, 3, 5, 7])

#### Reassigning the array

In [22]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [23]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [24]:
a[1,-2] = 13

In [25]:
a[:,2] = [3,10]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
# assingments    ----->5,12 should be replaced with 9,34
a[:,4] = [9,34]
a

array([[ 1,  2,  3,  4,  9,  6,  7],
       [ 8,  9, 10, 11, 34, 13, 14]])

*3-d example

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [29]:
# Get specific element (work outside in)
b[0,1,1]

4

In [30]:
# replace 
b[:,1,:] = [[9,9],[8,8]]


In [31]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [32]:
b   # assignment replace 1,2 with 4,5

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [33]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All 1s matrix
a=np.ones((2,2,2), dtype='int32')
print(a)
a.ndim

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


3

In [35]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [36]:
# Any other number (full_like)
np.full_like(a, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [37]:
# Random decimal numbers
np.random.rand(4,2)              # returns an array of random samples from the uniform distribution over [0,1] 

array([[0.18389938, 0.14907322],
       [0.5153663 , 0.24883799],
       [0.03938867, 0.5772251 ],
       [0.35656753, 0.99241624]])

In [38]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))      # Return random integers from low (inclusive) to high (exclusive).

array([[ 2,  6, -1],
       [ 0,  7,  4],
       [-2,  4,  2]])

In [39]:
# The identity matrix
a=np.identity(3)             #identy matrix is nothing but it prints "1" diagonally
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# To print the value diagonally
np.diagonal(a)               #it gives you the values of diagonal number

array([1., 1., 1.])

In [41]:
# giving proper example by including some condition

a=np.random.randint(30,size=(3,3))
print("printing a=\n",a)
b=np.diagonal(a)
print("\nprinting the diagonal values of a=",b)

printing a=
 [[13 12 27]
 [19 16 27]
 [29 15 14]]

printing the diagonal values of a= [13 16 14]


In [42]:
# Repeat an array                   #  it should be multi dimentional to do repeat function
a = np.array([[1,2,3]])
r1 = np.repeat(a,4, axis=1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [43]:
# Repeat an array                   #  it should be multi dimentional to do repeat function
a = np.array([[1,2,3]])
r1 = np.repeat(a,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
# you can use the flatten to convert any dimension in to 1 dimension
#lets take the above example
print("r1=\n",r1)
print("printing the dimension of r1=\n",r1.ndim)
r2=r1.flatten()
# Here we are going to convert the 2dimenson in to 1dimension
print("r2=\n",r2)
print("printing the converted dimension of(r1) r2=\n",r2.ndim)


r1=
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
printing the dimension of r1=
 2
r2=
 [1 2 3 1 2 3 1 2 3]
printing the converted dimension of(r1) r2=
 1


In [45]:
import numpy as np
a=np.array([1,5,9,7])
b=np.array([9,12,6,14])
np.repeat((a,b,a),(2,3,2),axis = 0)

array([[ 1,  5,  9,  7],
       [ 1,  5,  9,  7],
       [ 9, 12,  6, 14],
       [ 9, 12,  6, 14],
       [ 9, 12,  6, 14],
       [ 1,  5,  9,  7],
       [ 1,  5,  9,  7]])

##### Linear Algebra

In [46]:
# In matrix multiplication the number of column of first element should be equal to no of rows of the second element

#And the output of the matrix will be the no rows in first element and the number of column in the second element

a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)    #where in matrix multiplication there should be no of columns = no of rows

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [47]:
a = np.array([[3,4],[7,2],[5,9]])
b = np.array([[3,1,5],[6,9,7]])

print(a)
print(b)
c = np.matmul(a,b)
print(c)

[[3 4]
 [7 2]
 [5 9]]
[[3 1 5]
 [6 9 7]]
[[33 39 43]
 [33 25 49]
 [69 86 88]]


In [48]:
a=np.full((3,4),5)
b=np.ones((4,2),dtype="int")
print(a)
print(b)
print("\n")


c=np.matmul(a,b)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


[[20 20]
 [20 20]
 [20 20]]


In [49]:
540+8-45

503

In [50]:
# Find the determinant
#determent is only posible for square matrixe  ex:- number of rows is equal to no of columns

a=np.random.randint(10,size=(3,3))
print(a)
np.linalg.det(a)

[[8 6 8]
 [6 1 4]
 [4 6 4]]


47.999999999999986

##### Statistics

In [51]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

1

In [53]:
np.max(stats)

6

In [54]:
np.min(stats,axis=0)

array([1, 2, 3])

In [55]:
np.min(stats,axis=1)

array([1, 4])

In [56]:
np.max(stats, axis=1)

array([3, 6])

In [57]:
np.sum(stats)

21

### Reorganizing Arrays

In [58]:
# If you are performing the reshape operation then you have to consider that the size=to the multiple of shape


before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [59]:
a=np.array([[4,6,6,99],[4,9,5,32]])
print("a=\n",a)
a=a.flatten()
print("\nbefore reshape=",a)


a=a.reshape((2,2,2))
print("\nafter reshape=\n",a)

a=
 [[ 4  6  6 99]
 [ 4  9  5 32]]

before reshape= [ 4  6  6 99  4  9  5 32]

after reshape=
 [[[ 4  6]
  [ 6 99]]

 [[ 4  9]
  [ 5 32]]]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)
print('Before Reshaping =',arr)
print('After Reshaping =\n',newarr)

Before Reshaping = [ 1  2  3  4  5  6  7  8  9 10 11 12]
After Reshaping =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [61]:
#vertical stack(vstack)

# You can do vertical staking for one vector (vstack)
# If you want to perform for more than one vector you want to mention in the list
# If you are vertically stacking more than one array the size of array should be same

a=np.array([5,6,96,36,8,3])
np.vstack(a)

array([[ 5],
       [ 6],
       [96],
       [36],
       [ 8],
       [ 3]])

In [62]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [63]:
# Horizontal stack (hstack)

# # You can do horizontal staking for one vector (hstack)
# If you want to perform for more than one vector you want to mention in the list
# If you are horizontally stacking more than one array the size of array may be different not an issue

a=np.array([[4,6,6,99],[5,5,9,62]])
print(a)

f=a.flatten()
print("flatten=",f)

h=np.hstack(a)
print("hstack=",h)

[[ 4  6  6 99]
 [ 5  5  9 62]]
flatten= [ 4  6  6 99  5  5  9 62]
hstack= [ 4  6  6 99  5  5  9 62]


In [64]:
# Horizontal  stack 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2,h2])

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])